version: "3.9"
services:
  bot:
    build: .
    volumes:
      - ./config/example.env:/etc/bot/development.env
    environment:
      - "MONGO_HOST=mongo"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"